# Generated by Django 3.2 on 2022-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocodeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Долгота'),
        ),
    ]
