# Generated by Django 3.2 on 2022-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Адрес')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Долгота')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Широта')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего запроса к Геокодеру')),
            ],
        ),
    ]
