# Generated by Django 3.2 on 2022-08-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocodeapp', '0002_auto_20220827_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Долгота'),
        ),
    ]
