# Generated by Django 3.2 on 2022-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocodeapp', '0003_auto_20220827_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Адрес'),
        ),
    ]
