services:
  frontend:
    build:
      ./frontend
    container_name: frontend
    command: >
      sh -c "mv ./assets/* ./static/ -fv &&
             ./node_modules/.bin/parcel build ./bundles-src/index.js --dist-dir ./static --public-url='./'"
    volumes:
      - static:/app/static
    env_file: .env
    ports:
      - 8765:8765

  django_backend:
    build:
      ./backend
    container_name: backend
    command: >
      sh -c "python3 manage.py migrate --noinput && 
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - static:/app/static
      - ./.git:/app/.git
    env_file: .env
    depends_on:
      - frontend
      - db
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:15-bookworm
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    expose:
      - 5432
  
volumes:
  static:
  postgres_data:
  