# Generated by Django 3.2 on 2022-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220814_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('elec', 'Электронно'), ('cash', 'Наличные')], db_index=True, default='cash', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
