# Generated by Django 3.2 on 2022-08-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executable_orders', to='foodcartapp.restaurant', verbose_name='Ресторан, выполняющий заказ'),
        ),
    ]
