# Generated by Django 3.2 on 2022-09-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_orderitem_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='selected_restaurant',
        ),
    ]
