# Generated by Django 3.2 on 2022-08-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220812_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Необработанный'), ('1', 'Собирается'), ('2', 'Доставляется'), ('3', 'Выполнен')], default='0', max_length=1),
        ),
    ]
