services:
  frontend:
    image: star-burger-frontend
    container_name: star-burger-frontend
    volumes:
      - /var/www/docker-star-burger-site/staticfiles:/app/staticfiles
    env_file: .env
    ports:
      - 8765:8765

  django_backend:
    image: star-burger-backend
    container_name: star-burger-backend
    volumes:
      - /var/www/docker-star-burger-site/staticfiles:/app/staticfiles
      - ../.git:/app/.git
    env_file: .env
    depends_on:
      - db
      
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:15-bookworm
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    restart: always
    expose:
      - 5432
  
volumes:
  postgres_data:
  